/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jogo.view;

import br.com.jogo.ctrl.RodadaCTRL;
import br.com.jogo.negocio.Jogador;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author VictorKaiqui
 */
public class RodadaVIEW extends javax.swing.JDialog {

    /**
     * Creates new form RodadaVIEW
     */
    private RodadaCTRL controle;

    public RodadaVIEW(java.awt.Frame parent, boolean modal, List<Jogador> jogadores) {
        super(parent, modal);
        initComponents();

        perguntaTextPane.setEditable(false);
        respostaATextField.setEditable(false);
        respostaBTextField.setEditable(false);
        respostaCTextField.setEditable(false);
        respostaDTextField.setEditable(false);

        controle = new RodadaCTRL(this, jogadores);
        alternativaCertaARadioButton.addActionListener(controle);
        alternativaCertaBRadioButton.addActionListener(controle);
        alternativaCertaCRadioButton.addActionListener(controle);
        alternativaCertaDRadioButton.addActionListener(controle);
        proximoButton.addActionListener(controle);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alternativaCertaBRadioButton = new javax.swing.JRadioButton();
        alternativaCertaCRadioButton = new javax.swing.JRadioButton();
        respostaDTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        perguntaTextPane = new javax.swing.JTextPane();
        alternativaCertaARadioButton = new javax.swing.JRadioButton();
        ALabel = new javax.swing.JLabel();
        BLabel = new javax.swing.JLabel();
        alternativaCertaDRadioButton = new javax.swing.JRadioButton();
        CLabel = new javax.swing.JLabel();
        proximoButton = new javax.swing.JButton();
        DLabel = new javax.swing.JLabel();
        respostaATextField = new javax.swing.JTextField();
        respostaCTextField = new javax.swing.JTextField();
        respostaBTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(perguntaTextPane);

        ALabel.setText("A)");

        BLabel.setText("B)");

        CLabel.setText("C)");

        proximoButton.setText("Proximo");

        DLabel.setText("D)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(DLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(respostaDTextField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(CLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(respostaCTextField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ALabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(respostaATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(respostaBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alternativaCertaARadioButton)
                                .addComponent(alternativaCertaBRadioButton)
                                .addComponent(alternativaCertaCRadioButton)
                                .addComponent(alternativaCertaDRadioButton)))
                        .addComponent(proximoButton, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ALabel)
                            .addComponent(respostaATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(alternativaCertaARadioButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BLabel)
                            .addComponent(respostaBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(alternativaCertaBRadioButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CLabel)
                            .addComponent(respostaCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(alternativaCertaCRadioButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(alternativaCertaDRadioButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DLabel)
                            .addComponent(respostaDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                    .addComponent(proximoButton)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALabel;
    private javax.swing.JLabel BLabel;
    private javax.swing.JLabel CLabel;
    private javax.swing.JLabel DLabel;
    private javax.swing.JRadioButton alternativaCertaARadioButton;
    private javax.swing.JRadioButton alternativaCertaBRadioButton;
    private javax.swing.JRadioButton alternativaCertaCRadioButton;
    private javax.swing.JRadioButton alternativaCertaDRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane perguntaTextPane;
    private javax.swing.JButton proximoButton;
    private javax.swing.JTextField respostaATextField;
    private javax.swing.JTextField respostaBTextField;
    private javax.swing.JTextField respostaCTextField;
    private javax.swing.JTextField respostaDTextField;
    // End of variables declaration//GEN-END:variables

    public JLabel getALabel() {
        return ALabel;
    }

    public void setALabel(JLabel ALabel) {
        this.ALabel = ALabel;
    }

    public JLabel getBLabel() {
        return BLabel;
    }

    public void setBLabel(JLabel BLabel) {
        this.BLabel = BLabel;
    }

    public JLabel getCLabel() {
        return CLabel;
    }

    public void setCLabel(JLabel CLabel) {
        this.CLabel = CLabel;
    }

    public JLabel getDLabel() {
        return DLabel;
    }

    public void setDLabel(JLabel DLabel) {
        this.DLabel = DLabel;
    }

    public JRadioButton getAlternativaCertaARadioButton() {
        return alternativaCertaARadioButton;
    }

    public void setAlternativaCertaARadioButton(JRadioButton alternativaCertaARadioButton) {
        this.alternativaCertaARadioButton = alternativaCertaARadioButton;
    }

    public JRadioButton getAlternativaCertaBRadioButton() {
        return alternativaCertaBRadioButton;
    }

    public void setAlternativaCertaBRadioButton(JRadioButton alternativaCertaBRadioButton) {
        this.alternativaCertaBRadioButton = alternativaCertaBRadioButton;
    }

    public JRadioButton getAlternativaCertaCRadioButton() {
        return alternativaCertaCRadioButton;
    }

    public void setAlternativaCertaCRadioButton(JRadioButton alternativaCertaCRadioButton) {
        this.alternativaCertaCRadioButton = alternativaCertaCRadioButton;
    }

    public JRadioButton getAlternativaCertaDRadioButton() {
        return alternativaCertaDRadioButton;
    }

    public void setAlternativaCertaDRadioButton(JRadioButton alternativaCertaDRadioButton) {
        this.alternativaCertaDRadioButton = alternativaCertaDRadioButton;
    }

    public RodadaCTRL getControle() {
        return controle;
    }

    public void setControle(RodadaCTRL controle) {
        this.controle = controle;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextPane getPerguntaTextPane() {
        return perguntaTextPane;
    }

    public void setPerguntaTextPane(JTextPane perguntaTextPane) {
        this.perguntaTextPane = perguntaTextPane;
    }

    public JButton getProximoButton() {
        return proximoButton;
    }

    public void setProximoButton(JButton proximoButton) {
        this.proximoButton = proximoButton;
    }

    public JTextField getRespostaATextField() {
        return respostaATextField;
    }

    public void setRespostaATextField(JTextField respostaATextField) {
        this.respostaATextField = respostaATextField;
    }

    public JTextField getRespostaBTextField() {
        return respostaBTextField;
    }

    public void setRespostaBTextField(JTextField respostaBTextField) {
        this.respostaBTextField = respostaBTextField;
    }

    public JTextField getRespostaCTextField() {
        return respostaCTextField;
    }

    public void setRespostaCTextField(JTextField respostaCTextField) {
        this.respostaCTextField = respostaCTextField;
    }

    public JTextField getRespostaDTextField() {
        return respostaDTextField;
    }

    public void setRespostaDTextField(JTextField respostaDTextField) {
        this.respostaDTextField = respostaDTextField;
    }
}